### ISSUE TITLE
Documentation tracking issue

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#930]
Now that we have a basic docs layout (#890), we can work on the details. 

# Content

- [x] Replace landing page with "welcome" page. Similar to [Flashbots](https://docs.flashbots.net/). Much more to-the-point and less frontend hassle.
- [x] Quick start. Should explain how to run a Juno node with Docker.
- [x] Community. Descriptions of where to get help and offer help, encouragement to Tweet, etc.
- [ ] Contributing. Explains how to build from source and issue/PR etiquette. Maybe a description of the directory layout once that stabilizes.

# Branding

- [x] Favicon - the small image in the browser tab
- [x] Custom font.
- [x] CSS styling (light mode and dark mode). The default accent colors are green, yellow, and blue. We should change them to Juno's distinctive orange, navy, and white.

# Other

- [x] We need a sub-domain or sub-page on [nethermind.io](https://nethermind.io).
- [ ] [Algolia](https://www.algolia.com/) documentation search

Other note: we should use Docusaurus' [versioning](https://docusaurus.io/docs/versioning) feature moving forward. We can document each Juno version separately, and easily edit documentation for the `main` branch in PRs. No need for last-minute pre-release README editing.

**Comment by LordGhostX** [comment]
Closing this issue because https://github.com/NethermindEth/juno/pull/1857 includes a detailed README for running locally and implements `@easyops-cn/docusaurus-search-local` for searching (the docs are still manageable by it, and we can always switch to Algolia in the future)
